name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,16.x,18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g @angular/cli
        npm @angular/cdk@14.2.7
        npm @angular/material@14.2.7
        npm install
               
    - name: NPM Test
      run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          CI=true npm run test-headless
      env:
          CI: true
            npx webpack
 
